### ISSUE TITLE
ImportError: cannot import name 'CONDENSE_PROMPT' from 'templates.condense_prompt'

### ISSUE THREAD

**Issue by huhu42** [Haste171/langchain-chatbot#19]
Looks like it's from [this commit ](https://github.com/Haste171/langchain-chatbot/commit/79635a9a7c00b6f91a1c5f3409fa09b634f90ccc) 2 days ago 

I moved the `CONDENSE_PROMPT` out of the function to get around it

**Comment by Haste171** [comment]
Should be fixed

**Comment by YINING-WANG-3** [comment]
Sorry I'm a beginner, I'm still experiencing the same problem so how should I fix it? I'm not sure I understand what huhu said about “move the CONDENSE_PROMPT out of the function”
